1;;
4;;
4 + 2;;
2 *5 mod 10;;
5 mod 10;;
max_int;;
min_int;;
max_int + 1;;
min_int - 1;;
4;;
4.0;;
4.;;
2. +. 5. ;;
2<5;;
2.<5.;;
true;;
false;;
not false;;
not true;;
false && false;;
false || false;;
false || true;;
'a';;
"a";;
'ab';;
"ab";;
'a'=='b';;
'a'=='a';;
"ab"=="ab";;
'a'=="a";;
"ab"="ab";;
2.=2;;
float_of_int 2;;
2. = (float_of_int 2);;
int_of_float 2.;;
string_of_int(1+1);
int_of_char '1';;
char_of_int 50;;
let x =10; ;;
x;;
let x = x<15;;
let a=5 and b="b" and c=true;;
let i = 1 and j = i + 2;;
k;;
not true || true;;
(not true) || true;;
not (true || true);;
false && flase || false;;
(false && false) || true;;
false && (false || true);;
false && false || true;;
10<20;;
int = 10<(float_of_int 20);;
10 < int_of_float 20.;;
let x = 5;;
let y = 2.+.3.;;
let c = 'c';;
let capitalizedC = char_of_int((int_of_char c)-32);;
let x=5;;
let y=1;;
x+y;;
(1,2);;
let x = (1,2);;
1,2;;
let y = (1, "two", '3',4.);;
x;;
fst(x);;
fst x;;
snd((4,8));;
snd(1,2,3);;
snd 1,2;;
snd(1,2);;
[];;
[1];;
[1;2];;
['a';'a'];;
['a','a'];;
let y = ["1"; "2"; 'three];;
[1;2.];;
[1,2];;
[(1,2)];;
1;;[2;3];;
1::[2;3];;
let x=5;;
let y == [10,15];;
let y = [10,15];;
x::y;;
let y = [10;15];;
x;;y;;
let y = [10,15];;
x::y;;
let y = [10;15];;
x::y;;
let x = [x];;
x::y;;
let z = [[10];[15]];;
x;;
x::y;;
[1;2]@[3;4;5];;
let uppercase : char = char_of_int((int_of_char lowercase)-35);;
97-35;;
let lowercase='a';;
let uppercase = char_of_int(int_of_char(lowercase)-32);;
1::[2;3];;
[1;2;3;4;5]@[6;7;6];;
